# Lablab Bean Configuration

# Project settings
project:
  name: lablab-bean
  version: 0.1.0
  description: Dungeon crawler game with .NET backend and web terminal UI

# Pre-commit configuration
pre_commit:
  enabled: true
  auto_install: true
  hooks:
  - trailing-whitespace
  - end-of-file-fixer
  - check-yaml
  - markdownlint
