version: '3.8'

services:
  # Qdrant vector database for persistent memory storage
  qdrant:
    image: qdrant/qdrant:latest
    container_name: lablab-bean-qdrant
    ports:
    - 6333:6333      # HTTP API
    - 6334:6334      # gRPC API (optional)
    volumes:
    - qdrant_storage:/qdrant/storage
    environment:
    - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
    - lablab-bean-network
    restart: unless-stopped
    healthcheck:
      test: [CMD, wget, --quiet, --tries=1, --spider, http://localhost:6333/health]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  qdrant_storage:
    driver: local

networks:
  lablab-bean-network:
    driver: bridge
