[tool.ruff]
# Ruff configuration for Python code quality
# https://docs.astral.sh/ruff/

# Target Python 3.8+
target-version = "py38"

# Same as black
line-length = 88

# Enable auto-fixing
fix = true

# Exclude common directories
exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
]

[tool.ruff.lint]
# Enable pycodestyle (E), Pyflakes (F), isort (I), and more
select = [
    "E",     # pycodestyle errors
    "F",     # Pyflakes
    "I",     # isort (import sorting)
    "N",     # pep8-naming
    "UP",    # pyupgrade
    "B",     # flake8-bugbear
    "C4",    # flake8-comprehensions
    "SIM",   # flake8-simplify
    "RUF",   # Ruff-specific rules
]

# Ignore specific rules
ignore = [
    "E203",  # Whitespace before ':' (conflicts with black)
    "E501",  # Line too long (handled by formatter)
]

# Allow auto-fixing for all enabled rules
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Use double quotes for strings
quote-style = "double"

# Indent with spaces
indent-style = "space"

# Use \n line endings
line-ending = "auto"

# Format docstrings
docstring-code-format = true

[tool.ruff.lint.isort]
# Organize imports
known-first-party = ["lablab_bean"]

[tool.mypy]
# Type checking configuration
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
no_strict_optional = true

# Exclude directories
exclude = [
    'venv',
    '.venv',
    'node_modules',
    'build',
]
