version: '3'

tasks:
  build:
    desc: Build using NUKE default target (Compile)
    cmds:
      - pwsh -NoProfile -ExecutionPolicy Bypass -File build/nuke/build.ps1

  build:console:
    desc: Build console app via NUKE (Compile)
    cmds:
      - pwsh -NoProfile -ExecutionPolicy Bypass -File build/nuke/build.ps1 --target Compile --configuration Debug

  build:windows:
    desc: Build Windows app via NUKE (PublishWindows or Compile if configured)
    cmds:
      - pwsh -NoProfile -ExecutionPolicy Bypass -File build/nuke/build.ps1 --target PublishWindows --configuration Debug

  build:restore:
    desc: Restore via NUKE
    cmds:
      - pwsh -NoProfile -ExecutionPolicy Bypass -File build/nuke/build.ps1 --target Restore

  publish:
    desc: Publish console and windows apps into build/_artifacts/<version>/publish
    cmds:
      - pwsh -NoProfile -ExecutionPolicy Bypass -File build/nuke/build.ps1 --target PublishAll --configuration Debug

  release:
    desc: Full release packaging (includes website copy; may require website build)
    cmds:
      - pwsh -NoProfile -ExecutionPolicy Bypass -File build/nuke/build.ps1 --target Release --configuration Release

  build:artifacts:
    desc: Compile then publish (shortcut for build + publish)
    cmds:
      - task: build
      - task: publish
