using LablabBean.Plugins.Contracts;
using LablabBean.Plugins.Contracts.Attributes;
using LablabBean.Reporting.Contracts.Contracts;

namespace LablabBean.Reporting.Contracts.Proxies;

/// <summary>
/// Proxy implementation of IReportingService that delegates to the plugin registry.
/// The actual implementation is generated by the ProxyServiceGenerator.
/// </summary>
[RealizeService(typeof(IReportingService))]
public partial class ReportingServiceProxy : IReportingService
{
    private readonly IRegistry _registry;

    public ReportingServiceProxy(IRegistry registry)
    {
        _registry = registry ?? throw new System.ArgumentNullException(nameof(registry));
    }
}
