using LablabBean.Plugins.Contracts;
using LablabBean.Plugins.Contracts.Attributes;
using LablabBean.Reporting.Contracts.Contracts;

namespace LablabBean.Reporting.Contracts.Proxies;

/// <summary>
/// Proxy implementation of IReportRenderer that delegates to the plugin registry.
/// The actual implementation is generated by the ProxyServiceGenerator.
/// Returns the highest priority renderer (typically used for single renderer scenarios).
/// For multi-renderer scenarios, use IRegistry.GetAll&lt;IReportRenderer&gt;() directly.
/// </summary>
[RealizeService(typeof(IReportRenderer))]
[SelectionStrategy(SelectionMode.HighestPriority)]
public partial class ReportRendererProxy : IReportRenderer
{
    private readonly IRegistry _registry;

    public ReportRendererProxy(IRegistry registry)
    {
        _registry = registry ?? throw new System.ArgumentNullException(nameof(registry));
    }
}
