using System;
using LablabBean.Plugins.Contracts;
using LablabBean.Plugins.Contracts.Attributes;

namespace LablabBean.Contracts.ServiceHealth.Services.Proxy;

/// <summary>
/// Proxy implementation of IService that delegates to the plugin registry.
/// The actual implementation is generated by the ProxyServiceGenerator.
/// </summary>
[RealizeService(typeof(IService))]
public partial class Service : IService
{
    private readonly IRegistry _registry;

    public Service(IRegistry registry)
    {
        _registry = registry ?? throw new ArgumentNullException(nameof(registry));
    }
}
